### ISSUE TITLE
btn Icons doesnt render locally 

### ISSUE THREAD

**Issue by Ozzie-code-alt** [GhassenEljday/react-mobile-app-button#28]

**Comment by GhassenEljday** [comment]
Hey @Ozzie-code-alt 
Could you give us some information, perhaps some screenshots?

**Comment by Ozzie-code-alt** [comment]
hello hello @GhassenEljday  its this one right here, could you help me with this one please 
i tried re-installing it using pnpm, yarn and npm but still the same result


![image](https://github.com/GhassenEljday/react-mobile-app-button/assets/83016833/ea9b4fbd-96ee-450e-b00c-1bbd4e821eca)

**Comment by GhassenEljday** [comment]
Hey @Ozzie-code-alt 
I just tried it on Sandbox and locally and it all sims good, can you please send me a sandbox with your code?

https://codesandbox.io/p/sandbox/react-mobile-app-button-858grd?file=%2Fsrc%2FApp.tsx

**Comment by andreymaslovru** [comment]
@GhassenEljday @Ozzie-code-alt 
Yes, the images are really not rendered in Nextjs, in order to fix something, you need to specify an explicit path to the image. Watch and edit svg, you need to specify the url! To do this, in addition, click place in src: logo -> src: logo.src

<img width="788" alt="Снимок экрана 2024-03-20 в 02 51 23" src="https://github.com/GhassenEljday/react-mobile-app-button/assets/74611548/4e2800bb-8ccb-4791-99a2-8c76304bd3c3">

**Comment by GhassenEljday** [comment]
Hey @andreymaslovru 
Thank you so much for sharing more information about the issue, I'll see what I can do, however I would like to have as a collaborator if u want to.

**Comment by GhassenEljday** [comment]
Hey Guys,

We've got a new version on the way, packed with all the fixes needed for this issue.

Thank you for reporting

**Comment by iosifnicolae2** [comment]
could you please publish the release on npm?

thank you very much!

**Comment by GhassenEljday** [comment]
Hi, @iosifnicolae2.
We just released the latest version, which you may use right now.

Thank you for using our Package
